### ISSUE TITLE
Can not available in Godot 3.0?

### ISSUE THREAD

**Issue by zenogears** [brunosxs/SMRT-Godot#10]
When trying make Active, it say: base type not EditorPlugin.:(

**Comment by brunosxs** [comment]
Not yet, I don't have the time to work on smrt.

**Comment by zenogears** [comment]
Thanks for hope :) We are waiting )

**Comment by brunosxs** [comment]
Since 0e635388fc2ebeb4d4765e8e6e0d523e6767a91a the plugin is already usable in godot 3. No editor for now, but as a workaround, you can keep a godot 2 instance open and load the editor to edit the language file from there.

**Comment by zenogears** [comment]
Cool! But without editor it is all... crap :)
Thanks for work. Still waiting for working editor!

**Comment by christh** [comment]
Hi guys, not related to the editor but I've made a couple of PRs to fix a couple of things in Godot 3.

Many thanks btw brunosxs - this is a great piece of work.

**Comment by moizez102** [comment]
brunosxs will you complete the version of Godot 3? I really like your plugin and it will be difficult to leave it when godot 3.1 comes out

It is very useful, and easy to use, it would be very sad that it is not available for Godot 3


(also, sorry for my bad english xD)

**Comment by christh** [comment]
I might have a go at picking it up - I'm currently hand-editing the .lan file using Notepad++ - I'll see how long before that gets annoying ;) 

As brunosxs says though you can download Godot 2 just for the editor and use it to edit the language files there. Works fine.

**Comment by metaphoricalsasquash** [comment]
I am really looking forward to use this in Godot 3 as well. Ever since I discovered SMRT a few weeks ago, I keep coming back regularly to check if there is any progress. I'm just starting out, so I would not know where to start to fix it to make it usable in 3 or how to bring things from Godot2 over to 3 as it was suggested here.
This plugin would enable me to do so many things I would not be able to figure out on my own.

**Comment by brunosxs** [comment]
pull #14 made the editor compatible.

**Comment by metaphoricalsasquash** [comment]
YAY!!
