### ISSUE TITLE
Is there any plan to make the SMRT Plugin functioning in Godot 3.1?

### ISSUE THREAD

**Issue by metaphoricalsasquash** [brunosxs/SMRT-Godot#13]
Without having to resort to Godot 2.X for the dialog editor, I mean.

**Comment by brunosxs** [comment]
As stated in #10 , I don't have time to give attention to SMRT as much as I want. I'd need some time to look at the plugin and redo the entire GUI for the editor, which is not easy to do in a single shot, even more since I do it in my spare time.

**Comment by metaphoricalsasquash** [comment]
Aw. Thank you though for the reply!

**Comment by ellis-matthew4** [comment]
If you take a look at my fork, I updated the GUI to 3.0.6. It may work in 3.1, I haven't tested it.

**Comment by brunosxs** [comment]
Thanks to @ellis-matthew4 , the editor is now compatible with godot 3.0
happy coding guys.
Thanks again ellis.

**Comment by metaphoricalsasquash** [comment]
Yes, thank you!
