### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by Themaker482** [brunosxs/SMRT-Godot#2]
why this doesnt work on android?

**Comment by brunosxs** [comment]
Hi.
Godot by default, will only export files it recognizes as resources.
As the .lan files are simply json and are not standard resources in godot, you have to explicitly tell godot that it should also export the *.lan files.

You can do that in the export configuration, under the "Resources" tab.
See the pic:
![image](https://cloud.githubusercontent.com/assets/1557903/21202878/6698c464-c237-11e6-9d1c-82413439c436.png)

Assuming it worked when you tried in the pc, It should work without problems in android.

**Comment by Themaker482** [comment]
thanks, thats something i didnt know, i will see how works
