### ISSUE TITLE
"single_text" doesn't effect dialog_control function

### ISSUE THREAD

**Issue by bobokox** [brunosxs/SMRT-Godot#3]
Hey!

First, thank you for this great asset! i really love it.
But theres a problem when i use it with single text. if the last text from the language file had a question, the single text has a question too. and the _on_dialog_dialog_control( info ) function doesn't return a chapter named "single_text". it returns the full information of the last text from the language file.

greetings
bobokox

**Comment by brunosxs** [comment]
Thanks for the report.

I fixed the bug with 7687f366360a4fc38705fba68d626e2379de542e commit, but I won't have time to update on the assetlib for now. Still... better than leave the bug.
