### ISSUE TITLE
text offset dont match face offset?

### ISSUE THREAD

**Issue by Elmapul** [brunosxs/SMRT-Godot#6]
the text is under the face, due to different offsets.

**Comment by brunosxs** [comment]
Well that's strange, it should match.
I am really busy with college(and will for months to come), but send an example project with the bug so that when I have the time I can look and see if it is a bug in SMRT.

**Comment by brunosxs** [comment]
Since I can't reproduce the bug and I've got no answer, I'll close this issue.
