### ISSUE TITLE
Make SMRT-Godot 100% compatible with Godot 3.0

### ISSUE THREAD

**Issue by brunosxs** [brunosxs/SMRT-Godot#8]
As we are getting closer to the launch of Godot 3.0, I am leaving this enhancement here.
SMRT-Godot should probably be compatible with Godot 3.0 already, in the sense that it will work out of the box but it should have a bug or two.

The good news is that the worst bug it had, I have already fixed months ago:
Godot 3.0 removed the ButtonArray node in favor of the ButtonGroup. This is not a problem since I've refactored the answer system with the button groups some months ago.

The only bug that I'm aware of (also, since months ago) is a very small one in the panel. Something changed in the panel node from godot 2.X to the 3.X which causes some display errors on the plugin. I'll have a look and fix it as soon as Godot hits beta status. I'll do everything I can to make it compatible with both 2.X and 3.X versions, using the same codebase. But if not, I'll just separate those in different branches.

So yeah... just good news.

**Comment by LinuxUserGD** [comment]
Godot 3.0 stable launched yesterday. Any news on porting it to Godot 3?

**Comment by brunosxs** [comment]
I don't have time to work on SMRT and this trend will go for some time now. Sadly, I can't give a timeframe for it.
